[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name = "pyrepowiki-cli"
version = "0.2.1"
authors = [
  {name = "Joe Hoye Dow", email = "luxunisgod123@gmail.com"}
  ]
description = "CLI tool for querying DeepWiki/Google code wiki/Zread wiki documentation for ANY github repository"
readme = "README.md"
requires-python = ">=3.10"
license = "GPL v3"
license-files = ["LICENSE"]


dependencies = [
    "mcp>=1.0.0,<2.0.0", 
    "typer>=0.12.0", 
    "httpx>=0.27.0", 
    "rich>=13.0.0", 
    "websockets>=13.0.0"
]

[project.urls]
Homepage = "https://github.com/MaybeBio/Repowiki-cli"
Issues = "https://github.com/MaybeBio/Repowiki-cli/issues"

[project.scripts]
repowiki-cli = "repowiki.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/repowiki"]

[dependency-groups]
dev = ["pytest>=8.0.0", "pytest-asyncio>=0.23.0"]
